/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conexion;
import Controlador.ConstructorLogin;
import Controlador.ConstructorPersona;
import Controlador.ConstructorReiniciarClave;
import Modelo.CifrarClave;
import Modelo.FuncionesLogin;
import Modelo.FuncionesReinicioClave;
import java.awt.HeadlessException;
import java.awt.Image;
import java.security.NoSuchAlgorithmException;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class LoginHermes extends javax.swing.JFrame {

    /**
     * Creates new form LoginHermes
     */
    public LoginHermes() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnPrimerUso.setVisible(false);
        
        ImageIcon logo = new ImageIcon(getClass().getResource("/images/hermes.png"));
        ImageIcon icono = new ImageIcon(logo.getImage().getScaledInstance(Logo.getWidth(), Logo.getHeight(), Image.SCALE_DEFAULT));
        Logo.setIcon(icono);
        this.repaint();
        validarPrimerUsos();
        
    }
    
    public void validarPrimerUsos() {
        
        btnRecuperadores.setVisible(false);
        boolean datos = mensa.capturarEmpresa();
        if (datos == true) {
            
            boolean fe = mensa.capturarPersona();
            
            if (fe == true) {
                
                btnRegistro.setVisible(false);
                jLabel1.setVisible(false);
                btnRecuperadores.setVisible(true);
            }
            
        } else {
            txtUsuario.setVisible(false);
            txtContraseña.setVisible(false);
            usuario.setVisible(false);
            contra.setVisible(false);
            jSeparator1.setVisible(false);
            jSeparator2.setVisible(false);
            jLabel4.setVisible(false);
            jLabel2.setVisible(false);
            jLabel6.setVisible(false);
            btnPrimerUso.setVisible(false);
            btnIngresar.setVisible(false);
        }
    }

    //Objetos
    ConstructorLogin login = new ConstructorLogin();
    ConstructorReiniciarClave login2 = new ConstructorReiniciarClave();
    FuncionesLogin mensa = new FuncionesLogin();
    FuncionesReinicioClave mensa2 = new FuncionesReinicioClave();
    CifrarClave obj = new CifrarClave();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        contra = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        btnRecuperadores = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnPrimerUso = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido a Hermes");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 450, 80));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA:  ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(33, 33, 33));
        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 348, 32));

        txtContraseña.setBackground(new java.awt.Color(33, 33, 33));
        txtContraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(null);
        jPanel3.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 344, 32));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/login.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 178, 67));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 390, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 390, 10));

        contra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/password.png"))); // NOI18N
        jPanel3.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 34, 32));

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/user.png"))); // NOI18N
        jPanel3.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 30, 32));

        btnRecuperadores.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnRecuperadores.setForeground(new java.awt.Color(153, 153, 255));
        btnRecuperadores.setText("¿Has olvidado tu contraseña?");
        btnRecuperadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecuperadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuperadoresMouseClicked(evt);
            }
        });
        jPanel3.add(btnRecuperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/close.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel3.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        btnPrimerUso.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnPrimerUso.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimerUso.setText("¿Es tu primera ves usando Hermes?");
        btnPrimerUso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimerUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrimerUsoMouseClicked(evt);
            }
        });
        jPanel3.add(btnPrimerUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/minus.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanel3.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("Registrar Ahora");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 260, 80));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Iniciar Sesión");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 232, 53));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 490, 610));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hermes Software");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 337, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Derechos Reservados Hermes Software 2020");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 570, -1, -1));
        kGradientPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 180, 158, 145));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        if (txtUsuario.getText().trim().equals("") || txtContraseña.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Existen campos vacíos. Por favor, rellénelos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            
        } else if ("Usuario123".equals(txtContraseña.getText())) {
            
            login2.setUsuario(txtUsuario.getText());
            login2.setClave(txtContraseña.getText());
            
            if (mensa2.obtenerClaveGenerica(login2)) {
                
                PrimerUso log = new PrimerUso();
                log.setVisible(true);
                dispose();
            }            
        } else {
            EnviarDatos();
        }

        //Principal obj = new Principal();
        //obj.setVisible(true);
        //PrimerUso pu = new PrimerUso();
        //pu.setVisible(true);
        //this.dispose();

    }//GEN-LAST:event_btnIngresarActionPerformed
    
    void EnviarDatos() {
        try {
            
            if (true) {
                
                if (txtUsuario.getText().trim().equals("") || txtContraseña.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(this, "Existen campos vacíos. Por favor, rellénelos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
                    
                } else {
                    login.setUsuario(txtUsuario.getText());
                    String encriptar = "";
                    
                    try {
                        encriptar = obj.Encriptar(txtContraseña.getText());
                    } catch (NoSuchAlgorithmException e) {
                        Logger.getLogger(CifrarClave.class.getName()).log(Level.SEVERE, null, e);
                    }
                    login.setClave(encriptar);
                    
                    if (mensa.Login(login)) {
                        
                        if (login.getNivel() == 1) {
                            JOptionPane.showMessageDialog(this, "Bienvenido Root", "Root", JOptionPane.INFORMATION_MESSAGE);
                            mensa.Login(login);
                            Principal log = new Principal();
                            log.setVisible(true);
                            dispose();
                            
                        } else if (login.getNivel() == 2) {
                            JOptionPane.showMessageDialog(this, "Bienvenido Administrador", "Administrador", JOptionPane.INFORMATION_MESSAGE);
                            mensa.Login(login);
                            Principal log = new Principal();
                            log.setVisible(true);
                            dispose();
                            
                        } else if (login.getNivel() == 3) {
                            JOptionPane.showMessageDialog(this, "Bienvenido Coordinador", "Coordinador", JOptionPane.INFORMATION_MESSAGE);
                            mensa.Login(login);
                            Principal log = new Principal();
                            log.setVisible(true);
                            dispose();
                            
                        } else if (login.getNivel() == 4) {
                            JOptionPane.showMessageDialog(this, "Bienvenido Operador", "Operador", JOptionPane.INFORMATION_MESSAGE);
                            mensa.Login(login);
                            Principal log = new Principal();
                            log.setVisible(true);
                            dispose();
                            
                        } else if (login.getNivel() == 5) {
                            JOptionPane.showMessageDialog(this, "Error, un motorista no tiene acceso al sistema", "Usuario no indicado", JOptionPane.WARNING_MESSAGE);
                            mensa.Login(login);
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al iniciar sesión", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        }
                        
                    }
                }
                
            }
            
        } catch (Exception e) {
            System.err.println(e.toString());
            JOptionPane.showMessageDialog(this, "Error algo malo ha sucedido, consulte con el administrador ", "Error Critico", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        
        try {
            
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir del sistema?",
                    "Hermes Software", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                System.exit(0);
                
            } else {
                setDefaultCloseOperation(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error algo ha salido mal" + e);
        }
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnPrimerUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrimerUsoMouseClicked
        PrimerEmpresa pu = new PrimerEmpresa();
        pu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrimerUsoMouseClicked

    private void btnRecuperadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuperadoresMouseClicked
        RecuperadoresContraseña rc = new RecuperadoresContraseña();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecuperadoresMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        
        boolean pri = mensa.capturarPersona();
        boolean emp = mensa.capturarEmpresa();
        
        if (emp == false) {
            
            new PrimerEmpresa().setVisible(true);
            dispose();
            
        } else if (pri == false) {
            
            new PrimerRoot().setVisible(false);
            dispose();
            
        } else {
            
            txtUsuario.setVisible(false);
            txtContraseña.setVisible(false);
            usuario.setVisible(false);
            contra.setVisible(false);
            jSeparator1.setVisible(false);
            jSeparator2.setVisible(false);
            jLabel4.setVisible(false);
            jLabel2.setVisible(false);
            jLabel6.setVisible(false);
            btnPrimerUso.setVisible(false);
            btnIngresar.setVisible(false);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginHermes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginHermes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginHermes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginHermes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginHermes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnPrimerUso;
    private javax.swing.JLabel btnRecuperadores;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
