/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.PanelTipoCliente;

/**
 *
 * @author samue
 */
public class PanelOpciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelOpciones
     */
    public PanelOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDetalleRecurso = new javax.swing.JButton();
        btnTipoPersonal = new javax.swing.JButton();
        btnTipoViaje = new javax.swing.JButton();
        btnTipoCliente = new javax.swing.JButton();
        btnTipoPago = new javax.swing.JButton();
        btnTipoServicio = new javax.swing.JButton();
        btnTipoUnidad = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnEstadoPersonal = new javax.swing.JButton();
        btnEstados = new javax.swing.JButton();
        btnTipo = new javax.swing.JButton();
        btnEstadoServicio = new javax.swing.JButton();
        btnEstadoUnidad = new javax.swing.JButton();
        btnPreguntas = new javax.swing.JButton();
        btnDepartamento = new javax.swing.JButton();
        btnBitacora = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona a que tabla quieres ir");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Más Opciones");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        btnDetalleRecurso.setBackground(new java.awt.Color(153, 153, 255));
        btnDetalleRecurso.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnDetalleRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/inventory.png"))); // NOI18N
        btnDetalleRecurso.setText("Detalle Recurso");
        btnDetalleRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleRecursoActionPerformed(evt);
            }
        });
        add(btnDetalleRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 220, 100));

        btnTipoPersonal.setBackground(new java.awt.Color(153, 153, 255));
        btnTipoPersonal.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnTipoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/user.png"))); // NOI18N
        btnTipoPersonal.setText("Tipo Personal");
        btnTipoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoPersonalActionPerformed(evt);
            }
        });
        add(btnTipoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, 100));

        btnTipoViaje.setBackground(new java.awt.Color(153, 153, 255));
        btnTipoViaje.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnTipoViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/location.png"))); // NOI18N
        btnTipoViaje.setText("Tipo Viaje");
        btnTipoViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoViajeActionPerformed(evt);
            }
        });
        add(btnTipoViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 220, 100));

        btnTipoCliente.setBackground(new java.awt.Color(153, 153, 255));
        btnTipoCliente.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnTipoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/customer.png"))); // NOI18N
        btnTipoCliente.setText("Tipo Cliente");
        btnTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoClienteActionPerformed(evt);
            }
        });
        add(btnTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 220, 100));

        btnTipoPago.setBackground(new java.awt.Color(153, 153, 255));
        btnTipoPago.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnTipoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/credit-card.png"))); // NOI18N
        btnTipoPago.setText("Tipo Pago");
        btnTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoPagoActionPerformed(evt);
            }
        });
        add(btnTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 220, 100));

        btnTipoServicio.setBackground(new java.awt.Color(153, 153, 255));
        btnTipoServicio.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnTipoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/technical-support.png"))); // NOI18N
        btnTipoServicio.setText("Tipo Servicio");
        btnTipoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoServicioActionPerformed(evt);
            }
        });
        add(btnTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 220, 100));

        btnTipoUnidad.setBackground(new java.awt.Color(153, 153, 255));
        btnTipoUnidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnTipoUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/travel.png"))); // NOI18N
        btnTipoUnidad.setText("Tipo Unidad");
        btnTipoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoUnidadActionPerformed(evt);
            }
        });
        add(btnTipoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 220, 100));

        btnMarca.setBackground(new java.awt.Color(153, 153, 255));
        btnMarca.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/shield.png"))); // NOI18N
        btnMarca.setText("Marca");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });
        add(btnMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 220, 100));

        btnFactura.setBackground(new java.awt.Color(153, 153, 255));
        btnFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/recruitment.png"))); // NOI18N
        btnFactura.setText("Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        add(btnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 220, 100));

        btnEstadoPersonal.setBackground(new java.awt.Color(153, 153, 255));
        btnEstadoPersonal.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnEstadoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/user.png"))); // NOI18N
        btnEstadoPersonal.setText("Estado Personal");
        btnEstadoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoPersonalActionPerformed(evt);
            }
        });
        add(btnEstadoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, 100));

        btnEstados.setBackground(new java.awt.Color(33, 33, 33));
        btnEstados.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnEstados.setForeground(new java.awt.Color(255, 255, 255));
        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });
        add(btnEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 140, 50));

        btnTipo.setBackground(new java.awt.Color(33, 33, 33));
        btnTipo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnTipo.setText("Tipos");
        btnTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoActionPerformed(evt);
            }
        });
        add(btnTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 140, 50));

        btnEstadoServicio.setBackground(new java.awt.Color(153, 153, 255));
        btnEstadoServicio.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnEstadoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/technical-support.png"))); // NOI18N
        btnEstadoServicio.setText("Estado Servicio");
        btnEstadoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoServicioActionPerformed(evt);
            }
        });
        add(btnEstadoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 220, 100));

        btnEstadoUnidad.setBackground(new java.awt.Color(153, 153, 255));
        btnEstadoUnidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnEstadoUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/travel.png"))); // NOI18N
        btnEstadoUnidad.setText("Estado Unidad");
        btnEstadoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoUnidadActionPerformed(evt);
            }
        });
        add(btnEstadoUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 220, 100));

        btnPreguntas.setBackground(new java.awt.Color(153, 153, 255));
        btnPreguntas.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/contract.png"))); // NOI18N
        btnPreguntas.setText("Preguntas");
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });
        add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 220, 100));

        btnDepartamento.setBackground(new java.awt.Color(153, 153, 255));
        btnDepartamento.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/shield.png"))); // NOI18N
        btnDepartamento.setText("Departamento");
        btnDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentoActionPerformed(evt);
            }
        });
        add(btnDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 220, 100));

        btnBitacora.setBackground(new java.awt.Color(153, 153, 255));
        btnBitacora.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBitacora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/inventory.png"))); // NOI18N
        btnBitacora.setText("Bitacora");
        btnBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBitacoraActionPerformed(evt);
            }
        });
        add(btnBitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 220, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoPersonalActionPerformed
        // TODO add your handling code here:
        PanelTipoUsuario abrir = new PanelTipoUsuario();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnTipoPersonalActionPerformed

    private void btnTipoViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoViajeActionPerformed
        // TODO add your handling code here:
        PanelTipoViaje abrir = new PanelTipoViaje();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnTipoViajeActionPerformed

    private void btnTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoClienteActionPerformed
        // TODO add your handling code here:
        PanelTipoCliente abrir = new PanelTipoCliente();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnTipoClienteActionPerformed

    private void btnTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoPagoActionPerformed
        // TODO add your handling code here:
        PanelTipoPago abrir = new PanelTipoPago();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnTipoPagoActionPerformed

    private void btnTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoServicioActionPerformed
        // TODO add your handling code here:
        PanelTipoServicio abrir = new PanelTipoServicio();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnTipoServicioActionPerformed

    private void btnTipoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoUnidadActionPerformed
        // TODO add your handling code here:
        PanelTipoUnidad abrir = new PanelTipoUnidad();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnTipoUnidadActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        // TODO add your handling code here:
        PanelMarca abrir = new PanelMarca();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnDetalleRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleRecursoActionPerformed
        // TODO add your handling code here:
         PanelDetalleRecurso abrir = new PanelDetalleRecurso();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnDetalleRecursoActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        PanelFactura abrir = new PanelFactura();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnEstadoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoPersonalActionPerformed
        // TODO add your handling code here:
        PanelEstadoPersonal abrir = new PanelEstadoPersonal();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnEstadoPersonalActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        // TODO add your handling code here:
        btnTipoPersonal.setVisible(false);
        btnTipoViaje.setVisible(false);
        btnTipoCliente.setVisible(false);
        btnTipoPago.setVisible(false);
        btnTipoServicio.setVisible(false);
        btnTipoUnidad.setVisible(false);
        btnMarca.setVisible(false);
        btnDetalleRecurso.setVisible(false);
        btnFactura.setVisible(false);
        btnEstadoPersonal.setVisible(true);
        btnEstadoServicio.setVisible(true);
        btnEstadoUnidad.setVisible(true);
        btnDepartamento.setVisible(false);
        btnBitacora.setVisible(false);
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoActionPerformed
        // TODO add your handling code here:
        btnTipoPersonal.setVisible(true);
        btnTipoViaje.setVisible(true);
        btnTipoCliente.setVisible(true);
        btnTipoPago.setVisible(true);
        btnTipoServicio.setVisible(true);
        btnTipoUnidad.setVisible(true);
        btnMarca.setVisible(true);
        btnDetalleRecurso.setVisible(true);
        btnFactura.setVisible(true);
        btnEstadoPersonal.setVisible(false);
        btnEstadoServicio.setVisible(false);
        btnEstadoUnidad.setVisible(false);
        btnDepartamento.setVisible(true);
        btnBitacora.setVisible(true);
    }//GEN-LAST:event_btnTipoActionPerformed

    private void btnEstadoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoServicioActionPerformed
        // TODO add your handling code here:
        PanelEstadoServicio abrir = new PanelEstadoServicio();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnEstadoServicioActionPerformed

    private void btnEstadoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoUnidadActionPerformed
        // TODO add your handling code here:
        PanelEstadoUnidad abrir = new PanelEstadoUnidad();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnEstadoUnidadActionPerformed

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        // TODO add your handling code here:
        PanelPreguntas abrir = new PanelPreguntas();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentoActionPerformed
        PanelDepartamento abrir = new PanelDepartamento();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnDepartamentoActionPerformed

    private void btnBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBitacoraActionPerformed
        PanelBitacora abrir = new PanelBitacora();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnBitacoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBitacora;
    private javax.swing.JButton btnDepartamento;
    private javax.swing.JButton btnDetalleRecurso;
    private javax.swing.JButton btnEstadoPersonal;
    private javax.swing.JButton btnEstadoServicio;
    private javax.swing.JButton btnEstadoUnidad;
    private javax.swing.JButton btnEstados;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JButton btnTipo;
    private javax.swing.JButton btnTipoCliente;
    private javax.swing.JButton btnTipoPago;
    private javax.swing.JButton btnTipoPersonal;
    private javax.swing.JButton btnTipoServicio;
    private javax.swing.JButton btnTipoUnidad;
    private javax.swing.JButton btnTipoViaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
