/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conexion;
import Controlador.*;
import java.sql.Connection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author samue
 */
public class PanelReportes extends javax.swing.JPanel {

    /**
     * Creates new form PanelReportes
     */
    public PanelReportes() {
        initComponents();
        validarNivel();
    }

    public void validarNivel() {

        ConstructorLogin mensa = new ConstructorLogin();

        if (mensa.getNivel() == 1) {

        } else if (mensa.getNivel() == 2) {

        } else if (mensa.getNivel() == 3) {
            btnPersonal.setEnabled(false);
            btnServicios.setEnabled(false);
            btnViajes.setEnabled(false);

        } else if (mensa.getNivel() == 4) {
            btnPersonal.setEnabled(false);
            btnRecursos.setEnabled(false);
            btnClientes.setEnabled(false);
            btnUnidades.setEnabled(false);
            btnContratos.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRecursos = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnUnidades = new javax.swing.JButton();
        btnContratos = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setPreferredSize(new java.awt.Dimension(900, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona a que reportes desea ver");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reportes");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        btnRecursos.setBackground(new java.awt.Color(102, 153, 255));
        btnRecursos.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRecursos.setForeground(new java.awt.Color(0, 0, 0));
        btnRecursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/pencil.png"))); // NOI18N
        btnRecursos.setText("Recursos");
        btnRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursosActionPerformed(evt);
            }
        });
        add(btnRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 220, 100));

        btnPersonal.setBackground(new java.awt.Color(102, 153, 255));
        btnPersonal.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnPersonal.setForeground(new java.awt.Color(0, 0, 0));
        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/user.png"))); // NOI18N
        btnPersonal.setText("Personal");
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });
        add(btnPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 220, 100));

        btnViajes.setBackground(new java.awt.Color(102, 153, 255));
        btnViajes.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnViajes.setForeground(new java.awt.Color(0, 0, 0));
        btnViajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/location.png"))); // NOI18N
        btnViajes.setText("Viajes");
        btnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesActionPerformed(evt);
            }
        });
        add(btnViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 220, 100));

        btnClientes.setBackground(new java.awt.Color(102, 153, 255));
        btnClientes.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/customer.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 220, 100));

        btnServicios.setBackground(new java.awt.Color(102, 153, 255));
        btnServicios.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(0, 0, 0));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/technical-support.png"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 220, 100));

        btnUnidades.setBackground(new java.awt.Color(102, 153, 255));
        btnUnidades.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnUnidades.setForeground(new java.awt.Color(0, 0, 0));
        btnUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/travel.png"))); // NOI18N
        btnUnidades.setText("Unidades");
        btnUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadesActionPerformed(evt);
            }
        });
        add(btnUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 220, 100));

        btnContratos.setBackground(new java.awt.Color(102, 153, 255));
        btnContratos.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnContratos.setForeground(new java.awt.Color(0, 0, 0));
        btnContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/recruitment.png"))); // NOI18N
        btnContratos.setText("Contratos");
        btnContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratosActionPerformed(evt);
            }
        });
        add(btnContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 220, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursosActionPerformed
        // TODO add your handling code here:
        ParametrosRecurso abrir = new ParametrosRecurso();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnRecursosActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed

        ParametrosPersonal abrir = new ParametrosPersonal();
        abrir.setVisible(true);
//        try {
//            //se crea la conexion
//            Connection cn = new Conexion().conectar();
//            JasperReport jr = JasperCompileManager.compileReport("src/Reportes/reportePersonal.jrxml");
//            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
//            JasperViewer jv = new JasperViewer(jp);
//            jv.setVisible(true);
//
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }

    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        // TODO add your handling code here:
        ParametrosViaje abrir = new ParametrosViaje();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnViajesActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        ParametrosCliente abrir = new ParametrosCliente();
        abrir.setVisible(true);

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        
        ParametrosServicios abrir = new ParametrosServicios();
        abrir.setVisible(true);

    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadesActionPerformed
        // TODO add your handling code here:
        ParametrosUnidad abrir = new ParametrosUnidad();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnUnidadesActionPerformed

    private void btnContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratosActionPerformed
        ParametrosContrato abrir = new ParametrosContrato();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnContratosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnContratos;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnRecursos;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnUnidades;
    private javax.swing.JButton btnViajes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
