/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conexion;
import Controlador.ConstructorLogin;
import Controlador.ConstructorPrimerUso;
import Controlador.ConstructorReiniciarClave;
import Modelo.CifrarClave;
import Modelo.FuncionesPrimerUso;
import Modelo.FuncionesReinicioClave;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Alberto Ramirez
 */
public class PrimerUso extends javax.swing.JFrame {

    //Declaracion de atributos
    Connection con2;
    Statement orden;
    ResultSet rs;

    /**
     * Creates new form PrimerUso
     */
    public PrimerUso() {
        initComponents();
        setLocationRelativeTo(null);
        txtIDPersona.setVisible(false);
        txtIDEstado.setVisible(false);
        txtIntentos.setVisible(false);
        FuncionesPrimerUso Fpu = new FuncionesPrimerUso();
        cmbPregunta1.setModel(Fpu.obtenerPregunta1());
        cmbPregunta2.setModel(Fpu.obtenerPregunta2());
    }

    Conexion con = new Conexion();

    //Objetos
    FuncionesPrimerUso mensa = new FuncionesPrimerUso();
    ConstructorPrimerUso obj = new ConstructorPrimerUso();
    FuncionesReinicioClave mensa2 = new FuncionesReinicioClave();
    ConstructorReiniciarClave obj2 = new ConstructorReiniciarClave();
    CifrarClave obj3 = new CifrarClave();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbPregunta1 = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cmbPregunta2 = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtRespuesta1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        btnTerminar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        txtIntentos = new javax.swing.JTextField();
        txtIDEstado = new javax.swing.JTextField();
        txtIDPersona = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Primer uso de Hermes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CODIGO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 280, 10));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Respode a las preguntas con solo una palabra");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTRASEÑA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(33, 33, 33));
        txtCodigo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(null);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 275, 44));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 275, 10));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRMAR CONTRASEÑA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        txtConfirmarContraseña.setBackground(new java.awt.Color(33, 33, 33));
        txtConfirmarContraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmarContraseña.setBorder(null);
        txtConfirmarContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmarContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 275, 44));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 275, 10));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa lo solicitado para configurar tu usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PREGUNTA 1:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        cmbPregunta1.setBackground(new java.awt.Color(33, 33, 33));
        cmbPregunta1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbPregunta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 390, 35));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 390, 10));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PREGUNTA 2:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        cmbPregunta2.setBackground(new java.awt.Color(33, 33, 33));
        cmbPregunta2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbPregunta2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 390, 35));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 390, 10));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RESPUESTA:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        txtRespuesta1.setBackground(new java.awt.Color(33, 33, 33));
        txtRespuesta1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRespuesta1.setForeground(new java.awt.Color(255, 255, 255));
        txtRespuesta1.setBorder(null);
        txtRespuesta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuesta1KeyTyped(evt);
            }
        });
        jPanel1.add(txtRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 275, 35));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 280, 10));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RESPUESTA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, -1));

        txtRespuesta2.setBackground(new java.awt.Color(33, 33, 33));
        txtRespuesta2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRespuesta2.setForeground(new java.awt.Color(255, 255, 255));
        txtRespuesta2.setBorder(null);
        txtRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta2ActionPerformed(evt);
            }
        });
        txtRespuesta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuesta2KeyTyped(evt);
            }
        });
        jPanel1.add(txtRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 275, 35));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 280, 10));

        btnTerminar.setBackground(new java.awt.Color(140, 158, 255));
        btnTerminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/online.png"))); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.setActionCommand("");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, 190, 60));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/minus.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/close.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        txtIntentos.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.add(txtIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 40, 30));

        txtIDEstado.setBackground(new java.awt.Color(33, 33, 33));
        txtIDEstado.setText("1");
        jPanel1.add(txtIDEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 40, 30));

        txtIDPersona.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.add(txtIDPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 40, 30));

        txtContraseña.setBackground(new java.awt.Color(33, 33, 33));
        txtContraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(null);
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 275, 44));

        btnCancelar.setBackground(new java.awt.Color(140, 158, 255));
        btnCancelar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/trash.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta2ActionPerformed

    public void confirmarCodigo() {

        boolean confirmacion = mensa2.obtenerCodigo(obj2);
    }

    public void Registrar() {

        if (txtRespuesta1.getText().trim().equals("") || txtRespuesta2.getText().trim().equals("")
                || txtCodigo.getText().trim().equals("") || txtConfirmarContraseña.getText().trim().equals("")) {

            JOptionPane.showMessageDialog(this, "Existen campos vacíos. Por favor, rellenelos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);

        } else if (txtContraseña.getText() == null ? txtConfirmarContraseña.getText() != null : !txtContraseña.getText().equals(txtConfirmarContraseña.getText())) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden, por favor verifique los datos ingresados", "Credenciales Incorrectas", JOptionPane.WARNING_MESSAGE);

        } else if ("Usuario123".equals(txtContraseña.getText())) {
            JOptionPane.showMessageDialog(this, "No puedes ingresar una contraseña por defecto como tu nueva contraseña", "Credenciales Incorrectas", JOptionPane.WARNING_MESSAGE);

        } else if (cmbPregunta1.getSelectedIndex() == 0 && cmbPregunta2.getSelectedIndex() == 0 || cmbPregunta1.getSelectedIndex() == 1 && cmbPregunta2.getSelectedIndex() == 1 || cmbPregunta1.getSelectedIndex() == 2 && cmbPregunta2.getSelectedIndex() == 2 || cmbPregunta1.getSelectedIndex() == 3 && cmbPregunta2.getSelectedIndex() == 3 || cmbPregunta1.getSelectedIndex() == 4 && cmbPregunta2.getSelectedIndex() == 4 || cmbPregunta1.getSelectedIndex() == 5 && cmbPregunta2.getSelectedIndex() == 5) {
            JOptionPane.showMessageDialog(this, "Una pregunta esta siendo seleccionada varias veces. Verifique que las preguntas sean diferentes", "Preguntas Repetidas", JOptionPane.WARNING_MESSAGE);

        } else if (txtRespuesta1.getText() == txtRespuesta2.getText()) {
            JOptionPane.showMessageDialog(this, "No puedes responder lo mismo a diferentes preguntas", "Respuestas Iguales", JOptionPane.WARNING_MESSAGE);

        } else {

            if (txtCodigo.getText().equals("")) {

                JOptionPane.showMessageDialog(this, "El codigo de confirmación esta vacío", "Datos Incompletos", JOptionPane.WARNING_MESSAGE);

            } else if (!txtCodigo.getText().equals("")) {
                obj2.setConfirmacion(txtCodigo.getText());
                if (mensa2.obtenerCodigo(obj2)) {

                    JOptionPane.showMessageDialog(this, "Su codigo es correcto", "Proceso Exitoso", JOptionPane.INFORMATION_MESSAGE);
                    obj.setIdEstado(Integer.parseInt(txtIDEstado.getText()));
                    obj.setConfirmacion(txtCodigo.getText());
                    obj.setRespuesta(txtRespuesta1.getText());
                    obj.setRespuesta2(txtRespuesta2.getText());

                    int idPregunta1 = mensa.obtenerIdPregunta1(cmbPregunta1.getItemAt((cmbPregunta1.getSelectedIndex())));
                    int idPregunta2 = mensa.obtenerIdPregunta2(cmbPregunta1.getItemAt((cmbPregunta2.getSelectedIndex())));
                    obj.setIdPregunta(idPregunta1);
                    obj.setIdPregunta2(idPregunta2);

                    String encriptar = "";

                    try {
                        encriptar = obj3.Encriptar(txtContraseña.getText());
                    } catch (NoSuchAlgorithmException e) {
                        Logger.getLogger(CifrarClave.class.getName()).log(Level.SEVERE, null, e);
                    }
                    obj.setClave(encriptar);

                    if (mensa.actualizarPersona(obj)) {
                        LoginHermes log = new LoginHermes();
                        log.setVisible(true);
                        dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El codigo de confirmación no coincide", "Datos Erroneos", JOptionPane.WARNING_MESSAGE);
                }

            }

        }
    }

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        Registrar();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked

        try {

            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir del sistema, los datos se perderán?",
                    "Hermes Software", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                System.exit(0);

            } else {
                setDefaultCloseOperation(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error algo ha salido mal" + e);
        }
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (int) KeyEvent.VK_ENTER) && (car != (int) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtCodigo.getText().length() == 6) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped

        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtContraseña.getText().length() == 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }


    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void txtConfirmarContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarContraseñaKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtConfirmarContraseña.getText().length() == 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtConfirmarContraseñaKeyTyped

    private void txtRespuesta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuesta1KeyTyped
        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtRespuesta1.getText().length() == 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtRespuesta1KeyTyped

    private void txtRespuesta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuesta2KeyTyped
        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtRespuesta2.getText().length() == 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtRespuesta2KeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        try {

            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea cancelar el registro de su usuario y volver al inicio de sesión, los datos se perderán?",
                    "Hermes Software", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                LoginHermes obj = new LoginHermes();
                obj.setVisible(true);
                dispose();

            } else {
                setDefaultCloseOperation(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error algo ha salido mal" + e);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimerUso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox<String> cmbPregunta1;
    private javax.swing.JComboBox<String> cmbPregunta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConfirmarContraseña;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtIDEstado;
    private javax.swing.JTextField txtIDPersona;
    private javax.swing.JTextField txtIntentos;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    // End of variables declaration//GEN-END:variables
}
