/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conexion;
import Controlador.*;
import Modelo.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Alberto Ramirez
 */
public class PrimerRoot extends javax.swing.JFrame {

    //Declaracion de atributos
    Connection con2;
    Statement orden;
    ResultSet rs;
    int dias = -1;
    Validaciones no = new Validaciones();

    /**
     * Creates new form PrimerRoot
     */
    public PrimerRoot() {
        initComponents();
        setLocationRelativeTo(null);
        txtId.setVisible(false);
        txtEstado.setVisible(false);
        cmbTipo.setEnabled(false);
        cmbTipo.setVisible(false);
        cmbEmpresa.setEnabled(false);
        cmbEmpresa.setVisible(false);
        FuncionesPrimerUsoRoot root = new FuncionesPrimerUsoRoot();
        cmbPregunta1.setModel(root.obtenerPregunta1());
        cmbPregunta2.setModel(root.obtenerPregunta2());
        cmbTipo.setModel(root.obtenerTipoPersonaRoot());
        cmbEmpresa.setModel(root.obtenerEmpresa());
    }

    java.util.Date date = new java.util.Date();
    DateFormat fechaHora = new SimpleDateFormat("yyyy-MM-dd");
    String convertido = fechaHora.format(date);

    Conexion con = new Conexion();

    //Objetos
    FuncionesPrimerUsoRoot mensa = new FuncionesPrimerUsoRoot();
    ConstructorPrimerUso obj = new ConstructorPrimerUso();
    CifrarClave cifrar = new CifrarClave();
    Validaciones vali = new Validaciones();

    public void calcularDias() {

        Calendar inicio = dcNacimiento.getCalendar();
        Calendar today = Calendar.getInstance();
        dias = 1;
        while (inicio.before(today) || inicio.equals(today)) {
            dias++;
            inicio.add(Calendar.DATE, 1);
        }
    }

    public void claveRandom() {
        String clave = "";
        String clave2 = "";
        clave = UUID.randomUUID().toString().toUpperCase().substring(0, 6);
        clave2 = UUID.randomUUID().toString().toLowerCase().substring(0, 6);
        JOptionPane.showMessageDialog(null, "Clave sugerida: " + clave + clave2, "Credencial Sugerida", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtSeguro = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnMinimizar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbPregunta2 = new javax.swing.JComboBox<>();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        cmbPregunta1 = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtRespuesta1 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        dcNacimiento = new com.toedter.calendar.JDateChooser();
        txtEstado = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        jSeparator16 = new javax.swing.JSeparator();
        txtDUI = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txtDireccion = new javax.swing.JTextField();
        cmbEmpresa = new javax.swing.JComboBox<>();
        btnGenerica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Primer uso de Hermes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/close.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        btnTerminar.setBackground(new java.awt.Color(140, 158, 255));
        btnTerminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/online.png"))); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.setActionCommand("");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 190, 60));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Responde a estas preguntas (Te serviran mas adelante)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRES: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        txtNombre.setBackground(new java.awt.Color(33, 33, 33));
        txtNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 275, 35));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 275, 10));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DUI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 10));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PREGUNTA 2:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 400, 10));

        txtSeguro.setBackground(new java.awt.Color(33, 33, 33));
        txtSeguro.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtSeguro.setForeground(new java.awt.Color(255, 255, 255));
        txtSeguro.setBorder(null);
        txtSeguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeguroKeyTyped(evt);
            }
        });
        jPanel1.add(txtSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 275, 35));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 275, 10));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FECHA NACIMIENTO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        txtRespuesta2.setBackground(new java.awt.Color(33, 33, 33));
        txtRespuesta2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRespuesta2.setForeground(new java.awt.Color(255, 255, 255));
        txtRespuesta2.setBorder(null);
        txtRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta2ActionPerformed(evt);
            }
        });
        txtRespuesta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuesta2KeyTyped(evt);
            }
        });
        jPanel1.add(txtRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 275, 35));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 275, 10));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/minus.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N# SEGURO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RESPUESTA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(33, 33, 33));
        txtCorreo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 275, 35));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 275, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 280, 10));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("APELLIDOS:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        txtApellido.setBackground(new java.awt.Color(33, 33, 33));
        txtApellido.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 275, 35));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 275, 10));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USUARIO:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(33, 33, 33));
        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 275, 35));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ahora ingresaras tu datos personales (ROOT)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TELEFONO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        cmbPregunta2.setBackground(new java.awt.Color(33, 33, 33));
        cmbPregunta2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbPregunta2.setForeground(new java.awt.Color(255, 255, 255));
        cmbPregunta2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 400, 35));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 10));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PREGUNTA 1:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        cmbPregunta1.setBackground(new java.awt.Color(33, 33, 33));
        cmbPregunta1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbPregunta1.setForeground(new java.awt.Color(255, 255, 255));
        cmbPregunta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 400, 35));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 400, 10));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONFIRMA TU CONTRASEÑA:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, 280, 10));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RESPUESTA:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, -1, -1));

        txtRespuesta1.setBackground(new java.awt.Color(33, 33, 33));
        txtRespuesta1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRespuesta1.setForeground(new java.awt.Color(255, 255, 255));
        txtRespuesta1.setBorder(null);
        txtRespuesta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuesta1KeyTyped(evt);
            }
        });
        jPanel1.add(txtRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 275, 35));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 280, 10));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CORREO:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 275, 10));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 990, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DIRECCIÓN:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 40, 40));

        dcNacimiento.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(dcNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 280, 30));

        txtEstado.setText("1");
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 40));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 250, 40));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 510, 10));

        txtDUI.setBackground(new java.awt.Color(33, 33, 33));
        txtDUI.setBorder(null);
        txtDUI.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDUI.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(txtDUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 180, 30));

        txtTelefono.setBackground(new java.awt.Color(33, 33, 33));
        txtTelefono.setBorder(null);
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 30));

        txtContraseña.setBackground(new java.awt.Color(33, 33, 33));
        txtContraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(null);
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 342, 280, 30));

        txtConfirmarContraseña.setBackground(new java.awt.Color(33, 33, 33));
        txtConfirmarContraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmarContraseña.setBorder(null);
        txtConfirmarContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmarContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 280, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CONTRASEÑA:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 280, 10));

        txtDireccion.setBackground(new java.awt.Color(33, 33, 33));
        txtDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(null);
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 510, 40));

        cmbEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 250, 40));

        btnGenerica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/Line Chart.png"))); // NOI18N
        btnGenerica.setText("Generar");
        btnGenerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenericaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 987, 734));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked

        try {

            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir del sistema?",
                    "Hermes Software", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                System.exit(0);

            } else {
                setDefaultCloseOperation(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error algo ha salido mal" + e);
        }
    }//GEN-LAST:event_btnCerrarMouseClicked

    public void agregarRoot() {
        int ids = mensa.idIncremental();

        if (txtNombre.getText().trim().equals("") || txtApellido.getText().trim().equals("")
                || txtSeguro.getText().trim().equals("") || txtDUI.getText().trim().equals("") || txtTelefono.getText().trim().equals("")
                || txtUsuario.getText().trim().equals("") || txtDireccion.getText().trim().equals("")
                || txtCorreo.getText().trim().equals("") || dcNacimiento.getDate() == null
                || txtTelefono.getText().trim().equals("") || txtContraseña.getText().trim().equals("")
                || txtConfirmarContraseña.getText().equals("") || txtRespuesta1.getText().trim().equals("")
                || txtRespuesta2.getText().trim().equals("") || dias < 6570 || dias == -1) {

            if (dias < 6570) {
                dcNacimiento.setCalendar(null);
                JOptionPane.showMessageDialog(this, "Verifique que su fecha de nacimiento no sea menor a dieciocho años", "Campo no acorde a lo solicitado", JOptionPane.WARNING_MESSAGE);
            }

            JOptionPane.showMessageDialog(this, "Existen campos vacios. Porfavor rellenelos", "Campos Vacios", JOptionPane.WARNING_MESSAGE);

        } else if (txtContraseña.getText() == null ? txtConfirmarContraseña.getText() != null : !txtContraseña.getText().equals(txtConfirmarContraseña.getText())) {

            JOptionPane.showMessageDialog(this, "Las claves no coinciden, por faovr verifique los datos ingresados", "Credenciales incorrectas", JOptionPane.WARNING_MESSAGE);

        } else if ("Uusario123".equals(txtContraseña.getText())) {
            JOptionPane.showMessageDialog(this, "Usted esta intentando ingresar una clave generica, lo cual no es posible", "Credenciales Incorrectas", JOptionPane.WARNING_MESSAGE);

        } else if (cmbPregunta1.getSelectedIndex() == 0 && cmbPregunta2.getSelectedIndex() == 0 || cmbPregunta1.getSelectedIndex() == 1 && cmbPregunta2.getSelectedIndex() == 1 || cmbPregunta1.getSelectedIndex() == 2 && cmbPregunta2.getSelectedIndex() == 2 || cmbPregunta1.getSelectedIndex() == 3 && cmbPregunta2.getSelectedIndex() == 3 || cmbPregunta1.getSelectedIndex() == 4 && cmbPregunta2.getSelectedIndex() == 4 || cmbPregunta1.getSelectedIndex() == 5 && cmbPregunta2.getSelectedIndex() == 5) {
            JOptionPane.showMessageDialog(this, "Una pregunta esta siendo seleccionada varias veces. Verifique que las preguntas sean diferentes", "Preguntas Repetidas", JOptionPane.WARNING_MESSAGE);

        } else if (txtRespuesta1.getText() == null ? txtRespuesta2.getText() == null : txtRespuesta1.getText().equals(txtRespuesta2.getText())) {
            JOptionPane.showMessageDialog(this, "No puedes responder lo mismo a diferentes preguntas", "Respuestas Iguales", JOptionPane.WARNING_MESSAGE);

        } else if (vali.valCorreo(txtCorreo.getText()) == false) {
            JOptionPane.showMessageDialog(this, "El correo no es valido, por favor verifique los datos ingresados", "Correo no valido", JOptionPane.WARNING_MESSAGE);

        } else {

            obj.setRegistro(convertido);
            obj.setIdEstado(Integer.parseInt(txtEstado.getText()));
            obj.setCodigo(ids);
            obj.setNombres(txtNombre.getText());
            obj.setApellidos(txtApellido.getText());

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String startDateString = dateFormat.format(dcNacimiento.getDate());

            if (dias >= 6570) {
                obj.setNacimiento(startDateString);

            } else {
                System.out.println("" + dias);
                JOptionPane.showMessageDialog(this, "Debes ser mayor a 18 años");
            }

            obj.setDireccion(txtDireccion.getText());
            obj.setnSeguro(txtSeguro.getText());
            obj.setDui(txtDUI.getText());
            obj.setUsuario(txtUsuario.getText());
            obj.setCorreo(txtCorreo.getText());
            obj.setTelefono(txtTelefono.getText());

            String encriptar = "";

            try {

                encriptar = cifrar.Encriptar(txtContraseña.getText());

            } catch (NoSuchAlgorithmException e) {
                Logger.getLogger(CifrarClave.class.getName()).log(Level.SEVERE, null, e);
            }
            obj.setClave(encriptar);

            int idPregunta1 = mensa.obtenerIdPregunta1(cmbPregunta1.getItemAt(cmbPregunta1.getSelectedIndex()));
            int idPregunta2 = mensa.obtenerIdPregunta2(cmbPregunta2.getItemAt(cmbPregunta2.getSelectedIndex()));
            int idTipo = mensa.obtenerIdTipoPersonaRoot(cmbTipo.getItemAt(cmbTipo.getSelectedIndex()));
            int idEmpresa = mensa.obtenerIdEmpresa(cmbEmpresa.getItemAt(cmbEmpresa.getSelectedIndex()));
            obj.setIdPregunta(idPregunta1);
            obj.setIdPregunta2(idPregunta2);
            obj.setIdTipo(idTipo);
            obj.setIdEmpresa(idEmpresa);
            obj.setRespuesta(txtRespuesta1.getText());
            obj.setRespuesta2(txtRespuesta2.getText());

            if (mensa.agregarRoot(obj)) {
                LoginHermes log = new LoginHermes();
                log.setVisible(true);
                dispose();
            }

        }

    }

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed

        if ((txtNombre.getText().trim().equals("") || txtApellido.getText().trim().equals("")
                || txtSeguro.getText().trim().equals("") || txtDUI.getText().trim().equals("") || txtTelefono.getText().trim().equals("")
                || txtUsuario.getText().trim().equals("") || txtDireccion.getText().trim().equals("")
                || txtCorreo.getText().trim().equals("") || dcNacimiento.getDate() == null
                || txtTelefono.getText().trim().equals("") || txtContraseña.getText().trim().equals("")
                || txtConfirmarContraseña.getText().equals("") || txtRespuesta1.getText().trim().equals("")
                || txtRespuesta2.getText().trim().equals(""))) {

        } else {
            calcularDias();
        }

        agregarRoot();
//        LoginHermes lh = new LoginHermes();
//        lh.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void txtRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta2ActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        //Solo letras
        Character e;
        e = evt.getKeyChar();
        if (!Character.isLetter(e) && e != KeyEvent.VK_SPACE) {
            evt.consume();
        }

        //Validamos el limite de caracteres
        if (txtNombre.getText().length() == 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped

        //Solo letras
        Character e;
        e = evt.getKeyChar();
        if (!Character.isLetter(e) && e != KeyEvent.VK_SPACE) {
            evt.consume();
        }

        //Validamos el limite de caracteres
        if (txtApellido.getText().length() == 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtSeguroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguroKeyTyped

        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < '-') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Solo numeros
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo números");
        }

        //Validamos el limite de caracteres
        if (txtSeguro.getText().length() == 12) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtSeguroKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped

        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < '-') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtUsuario.getText().length() == 42) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped

        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < '-') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtCorreo.getText().length() == 60) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void btnGenericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenericaActionPerformed
        claveRandom();
    }//GEN-LAST:event_btnGenericaActionPerformed

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped

        //Validamos el limite de caracteres
        if (txtContraseña.getText().length() == 32) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void txtConfirmarContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarContraseñaKeyTyped

        //Validamos el limite de caracteres
        if (txtConfirmarContraseña.getText().length() == 32) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtConfirmarContraseñaKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped

        //Validamos el limite de caracteres
        if (txtDireccion.getText().length() == 55) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtRespuesta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuesta1KeyTyped

        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtRespuesta1.getText().length() == 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtRespuesta1KeyTyped

    private void txtRespuesta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuesta2KeyTyped

        //Validamos que no se puedan poner espacios
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z') && (car != (char) KeyEvent.VK_ENTER) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        //Validamos el limite de caracteres
        if (txtRespuesta2.getText().length() == 25) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite de caracteres");
        }
    }//GEN-LAST:event_txtRespuesta2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimerRoot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btnGenerica;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox<String> cmbEmpresa;
    private javax.swing.JComboBox<String> cmbPregunta1;
    private javax.swing.JComboBox<String> cmbPregunta2;
    private javax.swing.JComboBox<String> cmbTipo;
    private com.toedter.calendar.JDateChooser dcNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JFormattedTextField txtDUI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    private javax.swing.JTextField txtSeguro;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
