/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import java.awt.Dimension;
//import java.awt.FlowLayout;
import Controlador.ConstructorLogin;
import Controlador.ConstructorPersona;
import java.awt.HeadlessException;
import java.awt.Image;
//import java.awt.Toolkit;
import javax.swing.ImageIcon;
//import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
//import java.time.LocalDateTime;
//import java.time.format.DateTimeFormatter;
//import java.util.Date;
//import javax.swing.JButton;
//import javax.swing.JPanel;

/**
 *
 * @author samue
 */
public class Principal extends javax.swing.JFrame implements ActionListener {

    Home Home = new Home();
    PanelFondo PanelFondo = new PanelFondo();
    PanelUsuarios PanelUsuarios = new PanelUsuarios();
    PanelViajes PanelViajes = new PanelViajes();
    PanelContrato PanelContrato = new PanelContrato();
    PanelServicio PanelServicio = new PanelServicio();
    PanelClientes PanelClientes = new PanelClientes();
    PanelUnidades PanelUnidades = new PanelUnidades();
    PanelInventario PanelInventario = new PanelInventario();
    PanelRecursos PanelRecursos = new PanelRecursos();
    PanelOpciones PanelOpciones = new PanelOpciones();
    PanelReportes PanelReportes = new PanelReportes();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLayout(null);
        this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Hermes Software");
        setLocationRelativeTo(null);

        ImageIcon logo = new ImageIcon(getClass().getResource("/images/hermes.png"));
        ImageIcon icono = new ImageIcon(logo.getImage().getScaledInstance(Logo.getWidth(), Logo.getHeight(), Image.SCALE_DEFAULT));
        Logo.setIcon(icono);

        btnHome1.addActionListener(this);
        btnUsuarios.addActionListener(this);
        btnViajes.addActionListener(this);
        btnContratos.addActionListener(this);
        btnServicios.addActionListener(this);
        btnClientes.addActionListener(this);
        btnUnidades.addActionListener(this);
        //btnInventario.addActionListener(this);
        btnRecursos.addActionListener(this);
        //btnFacturas.addActionListener(this);
        btnMas.addActionListener(this);
        btnReportes.addActionListener(this);
        validarNivel();

    }

    public void validarNivel() {
        ConstructorLogin mensa = new ConstructorLogin();

        if (mensa.getNivel() == 1) {

        } else if (mensa.getNivel() == 2) {

        } else if (mensa.getNivel() == 3) {
            btnUsuarios.setVisible(false);
            btnMas.setVisible(false);
            btnReportes.setVisible(true);

        } else if (mensa.getNivel() == 4) {
            btnUsuarios.setVisible(false);
            btnMas.setVisible(false);
            btnReportes.setVisible(true);
            btnContratos.setVisible(false);
            btnUnidades.setVisible(false);
            btnRecursos.setVisible(false);
            btnClientes.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barradenavegacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnHome1 = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JButton();
        nombre2 = new javax.swing.JLabel();
        btnUsuarios = new rsbuttoncustom.RSButtonCustom();
        btnContratos = new rsbuttoncustom.RSButtonCustom();
        btnClientes = new rsbuttoncustom.RSButtonCustom();
        btnUnidades = new rsbuttoncustom.RSButtonCustom();
        btnServicios = new rsbuttoncustom.RSButtonCustom();
        btnRecursos = new rsbuttoncustom.RSButtonCustom();
        btnViajes = new rsbuttoncustom.RSButtonCustom();
        btnReportes = new rsbuttoncustom.RSButtonCustom();
        btnMas = new rsbuttoncustom.RSButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barradenavegacion.setBackground(new java.awt.Color(20, 17, 17));
        barradenavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido a Hermes Software");
        barradenavegacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 188, 40));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/close.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        barradenavegacion.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 28, 40));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/minus.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        barradenavegacion.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 23, 37));

        btnHome1.setBackground(new java.awt.Color(20, 17, 17));
        btnHome1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(20, 17, 17));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/browser.png"))); // NOI18N
        btnHome1.setBorder(null);
        btnHome1.setBorderPainted(false);
        btnHome1.setContentAreaFilled(false);
        btnHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barradenavegacion.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        getContentPane().add(barradenavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 40));

        panelContenedor.setBackground(new java.awt.Color(51, 51, 51));
        panelContenedor.setForeground(new java.awt.Color(255, 255, 255));
        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 960, 660));

        kGradientPanel1.setBackground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 95, 95));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 330, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 330, 10));

        btnCerrarSesion.setBackground(new java.awt.Color(102, 153, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setOpaque(true);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 221, 50));

        nombre2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 22)); // NOI18N
        nombre2.setForeground(new java.awt.Color(0, 0, 0));
        nombre2.setText("Hermes Software");
        kGradientPanel1.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 20));

        btnUsuarios.setBackground(new java.awt.Color(102, 153, 255));
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/user.png"))); // NOI18N
        btnUsuarios.setText("Personal");
        btnUsuarios.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, -1));

        btnContratos.setBackground(new java.awt.Color(102, 153, 255));
        btnContratos.setForeground(new java.awt.Color(0, 0, 0));
        btnContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/contract.png"))); // NOI18N
        btnContratos.setText("  Contratos");
        btnContratos.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 290, -1));

        btnClientes.setBackground(new java.awt.Color(102, 153, 255));
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/customer.png"))); // NOI18N
        btnClientes.setText(" Clientes");
        btnClientes.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 290, -1));

        btnUnidades.setBackground(new java.awt.Color(102, 153, 255));
        btnUnidades.setForeground(new java.awt.Color(0, 0, 0));
        btnUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/travel.png"))); // NOI18N
        btnUnidades.setText(" Unidades");
        btnUnidades.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 290, -1));

        btnServicios.setBackground(new java.awt.Color(102, 153, 255));
        btnServicios.setForeground(new java.awt.Color(0, 0, 0));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/technical-support.png"))); // NOI18N
        btnServicios.setText(" Servicios");
        btnServicios.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 290, -1));

        btnRecursos.setBackground(new java.awt.Color(102, 153, 255));
        btnRecursos.setForeground(new java.awt.Color(0, 0, 0));
        btnRecursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/pencil.png"))); // NOI18N
        btnRecursos.setText(" Recursos");
        btnRecursos.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 290, -1));

        btnViajes.setBackground(new java.awt.Color(102, 153, 255));
        btnViajes.setForeground(new java.awt.Color(0, 0, 0));
        btnViajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/location.png"))); // NOI18N
        btnViajes.setText(" Viajes");
        btnViajes.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 290, -1));

        btnReportes.setBackground(new java.awt.Color(102, 153, 255));
        btnReportes.setForeground(new java.awt.Color(0, 0, 0));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/seo-report.png"))); // NOI18N
        btnReportes.setText(" Reportes");
        btnReportes.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 290, -1));

        btnMas.setBackground(new java.awt.Color(102, 153, 255));
        btnMas.setForeground(new java.awt.Color(0, 0, 0));
        btnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/more.png"))); // NOI18N
        btnMas.setText(" Más Opciones");
        btnMas.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        kGradientPanel1.add(btnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 290, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 330, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        try {

            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea cerrar sesión y regresar al inicio de sesión?",
                    "Hermes Software", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                LoginHermes obj = new LoginHermes();
                obj.setVisible(true);
                dispose();

            } else {
                setDefaultCloseOperation(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error algo ha salido mal" + e);
        }

    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked

        try {

            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir del sistema sin antes cerrar sesión?",
                    "Hermes Software", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                System.exit(0);

            } else {
                setDefaultCloseOperation(0);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error algo ha salido mal" + e);
        }
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel barradenavegacion;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btnCerrarSesion;
    private rsbuttoncustom.RSButtonCustom btnClientes;
    private rsbuttoncustom.RSButtonCustom btnContratos;
    private javax.swing.JButton btnHome1;
    private rsbuttoncustom.RSButtonCustom btnMas;
    private javax.swing.JLabel btnMinimizar;
    private rsbuttoncustom.RSButtonCustom btnRecursos;
    private rsbuttoncustom.RSButtonCustom btnReportes;
    private rsbuttoncustom.RSButtonCustom btnServicios;
    private rsbuttoncustom.RSButtonCustom btnUnidades;
    private rsbuttoncustom.RSButtonCustom btnUsuarios;
    private rsbuttoncustom.RSButtonCustom btnViajes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object evt = e.getSource();

        if (evt.equals(btnUsuarios)) {
            panelContenedor.add(PanelUsuarios);
            PanelUsuarios.setVisible(true);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);

        } else if (evt.equals(btnViajes)) {
            panelContenedor.add(PanelViajes);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(true);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);
        } else if (evt.equals(btnContratos)) {
            panelContenedor.add(PanelContrato);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(true);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);
        } else if (evt.equals(btnServicios)) {
            panelContenedor.add(PanelServicio);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(true);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);
        } else if (evt.equals(btnClientes)) {
            panelContenedor.add(PanelClientes);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(true);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);
        } else if (evt.equals(btnUnidades)) {
            panelContenedor.add(PanelUnidades);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(true);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);
        } else if (evt.equals(btnRecursos)) {
            panelContenedor.add(PanelRecursos);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(true);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);

        } else if (evt.equals(btnHome1)) {
            panelContenedor.add(Home);
            //panelContenedor.setVisible(true);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelFondo.setVisible(false);
            PanelOpciones.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(true);
        } else if (evt.equals(btnMas)) {
            panelContenedor.add(PanelOpciones);
            //panelContenedor.setVisible(true);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelFondo.setVisible(false);
            PanelReportes.setVisible(false);
            Home.setVisible(false);
            PanelOpciones.setVisible(true);
        } else if (evt.equals(btnReportes)) {
            panelContenedor.add(PanelReportes);
            //panelContenedor.setVisible(true);
            PanelUsuarios.setVisible(false);
            PanelFondo.setVisible(false);
            PanelViajes.setVisible(false);
            PanelContrato.setVisible(false);
            PanelServicio.setVisible(false);
            PanelClientes.setVisible(false);
            PanelUnidades.setVisible(false);
            PanelInventario.setVisible(false);
            PanelRecursos.setVisible(false);
            PanelFondo.setVisible(false);
            PanelReportes.setVisible(true);
            Home.setVisible(false);
            PanelOpciones.setVisible(false);
        }
    }
}
