/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.RecuperadoresContraseña;

/**
 *
 * @author samue
 */
public class RecuperadorCorreo extends javax.swing.JFrame {

    /**
     * Creates new form RecuperadorCorreo
     */
    public RecuperadorCorreo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnEnviar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnRecuperadores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtNuevaContraseña = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        btnGuardar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        btnVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("INGRESA EL CODIGO:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(51, 51, 51));
        txtCodigo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(null);
        txtCodigo.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 305, 35));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 305, 10));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("VERIFICA TU CORREO:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtCorreo1.setBackground(new java.awt.Color(51, 51, 51));
        txtCorreo1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo1.setBorder(null);
        txtCorreo1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 305, 35));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 305, 10));

        btnEnviar.setBackground(new java.awt.Color(204, 204, 204));
        btnEnviar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/mail.png"))); // NOI18N
        btnEnviar.setText("Enviar Codigo");
        jPanel2.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 160, 50));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnGuardar.setText("Verificar");
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 160, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 786, 200));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recuperador por Correo Electronico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/close.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 32));

        btnRecuperadores.setBackground(new java.awt.Color(204, 204, 204));
        btnRecuperadores.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnRecuperadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosbotones/recu.png"))); // NOI18N
        btnRecuperadores.setText("Volver a Recuperadores");
        btnRecuperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperadoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecuperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 190, 66));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NUEVA CONTRASEÑA:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txtNuevaContraseña.setBackground(new java.awt.Color(51, 51, 51));
        txtNuevaContraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtNuevaContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtNuevaContraseña.setBorder(null);
        txtNuevaContraseña.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 305, 35));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 305, 10));

        btnGuardar1.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnGuardar1.setText("Guardar");
        jPanel3.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 130, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 786, 140));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VERIFICA TU USUARIO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        txtUsuario1.setBackground(new java.awt.Color(33, 33, 33));
        txtUsuario1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario1.setBorder(null);
        txtUsuario1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 305, 35));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 305, 10));

        btnVerificar.setBackground(new java.awt.Color(204, 204, 204));
        btnVerificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnVerificar.setText("Verificar");
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnRecuperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperadoresActionPerformed
        RecuperadoresContraseña rc = new RecuperadoresContraseña();
        rc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRecuperadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperadorCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperadorCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperadorCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperadorCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperadorCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnRecuperadores;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtNuevaContraseña;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
